jobs:
  run-specs-with-mysql:
    executor: solidusio_extensions/mysql
    steps:
      - solidusio_extensions/run-tests
  run-specs-with-postgres:
    executor: solidusio_extensions/postgres
    steps:
      - solidusio_extensions/run-tests
orbs:
  solidusio_extensions: solidusio/extensions@volatile
version: 2.1
workflows:
  Run specs on supported Solidus versions:
    jobs:
      - run-specs-with-postgres
      - run-specs-with-mysql
  Weekly run specs against master:
    jobs:
      - run-specs-with-postgres
      - run-specs-with-mysql
    triggers:
      - schedule:
          cron: 0 0 * * 4
          filters:
            branches:
              only:
                - master
